export const vehicles = [
  { id: 1,   licensePlate: 'EV-001', make: 'Tesla',     model: 'Model 3',              year: 2023, driverId: 1,       colour: 'White',   range: 358 },
  { id: 2,   licensePlate: 'EV-002', make: 'Tesla',     model: 'Model Y',              year: 2024, driverId: 2,         colour: 'Black',   range: 330 },
  { id: 3,   licensePlate: 'EV-003', make: 'Tesla',     model: 'Model S',              year: 2022, driverId: 3,      colour: 'Red',     range: 405 },
  { id: 4,   licensePlate: 'EV-004', make: 'Tesla',     model: 'Model X',              year: 2023, driverId: 4,       colour: 'Silver',  range: 348 },
  { id: 5,   licensePlate: 'EV-005', make: 'Rivian',    model: 'R1T',                  year: 2023, driverId: 5,     colour: 'Green',   range: 314 },
  { id: 6,   licensePlate: 'EV-006', make: 'Rivian',    model: 'R1S',                  year: 2024, driverId: 6,        colour: 'Blue',    range: 321 },
  { id: 7,   licensePlate: 'EV-007', make: 'Ford',      model: 'F-150 Lightning',      year: 2023, driverId: 7,   colour: 'Grey',    range: 320 },
  { id: 8,   licensePlate: 'EV-008', make: 'Ford',      model: 'Mustang Mach-E',       year: 2022, driverId: 8,         colour: 'White',   range: 312 },
  { id: 9,   licensePlate: 'EV-009', make: 'Chevy',     model: 'Bolt EV',              year: 2023, driverId: 9,        colour: 'Yellow',  range: 259 },
  { id: 10,  licensePlate: 'EV-010', make: 'Chevy',     model: 'Silverado EV',         year: 2024, driverId: 10,        colour: 'Black',   range: 400 },
  { id: 11,  licensePlate: 'EV-011', make: 'Hyundai',   model: 'IONIQ 6',              year: 2023, driverId: 11,        colour: 'Blue',    range: 361 },
  { id: 12,  licensePlate: 'EV-012', make: 'Hyundai',   model: 'IONIQ 5',              year: 2022, driverId: 12,      colour: 'White',   range: 303 },
  { id: 13,  licensePlate: 'EV-013', make: 'Kia',       model: 'EV6',                  year: 2023, driverId: 13,        colour: 'Orange',  range: 310 },
  { id: 14,  licensePlate: 'EV-014', make: 'Kia',       model: 'EV9',                  year: 2024, driverId: 14,    colour: 'Silver',  range: 304 },
  { id: 15,  licensePlate: 'EV-015', make: 'BMW',       model: 'iX',                   year: 2023, driverId: 15,       colour: 'Black',   range: 324 },
  { id: 16,  licensePlate: 'EV-016', make: 'BMW',       model: 'i4',                   year: 2022, driverId: 16,         colour: 'Grey',    range: 301 },
  { id: 17,  licensePlate: 'EV-017', make: 'Mercedes',  model: 'EQS',                  year: 2023, driverId: 17,       colour: 'White',   range: 350 },
  { id: 18,  licensePlate: 'EV-018', make: 'Mercedes',  model: 'EQB',                  year: 2024, driverId: 18,         colour: 'Blue',    range: 243 },
  { id: 19,  licensePlate: 'EV-019', make: 'Audi',      model: 'Q8 e-tron',            year: 2023, driverId: 19,      colour: 'Red',     range: 285 },
  { id: 20,  licensePlate: 'EV-020', make: 'Audi',      model: 'A6 e-tron',            year: 2024, driverId: 20,     colour: 'Silver',  range: 370 },
  { id: 21,  licensePlate: 'EV-021', make: 'Volvo',     model: 'EX90',                 year: 2024, driverId: 21,         colour: 'Black',   range: 300 },
  { id: 22,  licensePlate: 'EV-022', make: 'Volvo',     model: 'C40 Recharge',         year: 2023, driverId: 22,       colour: 'Green',   range: 226 },
  { id: 23,  licensePlate: 'EV-023', make: 'Polestar',  model: 'Polestar 2',           year: 2022, driverId: 23,     colour: 'White',   range: 270 },
  { id: 24,  licensePlate: 'EV-024', make: 'Polestar',  model: 'Polestar 3',           year: 2024, driverId: 24,         colour: 'Grey',    range: 315 },
  { id: 25,  licensePlate: 'EV-025', make: 'Lucid',     model: 'Air Pure',             year: 2023, driverId: 25,       colour: 'White',   range: 410 },
  { id: 26,  licensePlate: 'EV-026', make: 'Lucid',     model: 'Air Grand Touring',    year: 2024, driverId: 26,      colour: 'Red',     range: 516 },
  { id: 27,  licensePlate: 'EV-027', make: 'Nio',       model: 'ET5',                  year: 2023, driverId: 27,            colour: 'Blue',    range: 329 },
  { id: 28,  licensePlate: 'EV-028', make: 'Nio',       model: 'ET7',                  year: 2024, driverId: 28,     colour: 'Black',   range: 373 },
  { id: 29,  licensePlate: 'EV-029', make: 'VW',        model: 'ID.4',                 year: 2023, driverId: 29,       colour: 'White',   range: 275 },
  { id: 30,  licensePlate: 'EV-030', make: 'VW',        model: 'ID.Buzz',              year: 2024, driverId: 30,        colour: 'Orange',  range: 230 },
  { id: 31,  licensePlate: 'EV-031', make: 'Subaru',    model: 'Solterra',             year: 2023, driverId: 31,       colour: 'Blue',    range: 222 },
  { id: 32,  licensePlate: 'EV-032', make: 'Toyota',    model: 'bZ4X',                 year: 2022, driverId: 32,       colour: 'Silver',  range: 252 },
  { id: 33,  licensePlate: 'EV-033', make: 'Nissan',    model: 'Ariya',                year: 2023, driverId: 33,        colour: 'Grey',    range: 289 },
  { id: 34,  licensePlate: 'EV-034', make: 'Nissan',    model: 'Leaf',                 year: 2022, driverId: 34,        colour: 'White',   range: 212 },
  { id: 35,  licensePlate: 'EV-035', make: 'GMC',       model: 'Hummer EV',            year: 2023, driverId: 35,    colour: 'Black',   range: 329 },
  { id: 36,  licensePlate: 'EV-036', make: 'Cadillac',  model: 'LYRIQ',                year: 2024, driver: 'Kevin O\'Brien',     colour: 'Red',     range: 314 },
  { id: 37,  licensePlate: 'EV-037', make: 'Jeep',      model: 'Avenger EV',           year: 2023, driverId: 37,     colour: 'Green',   range: 248 },
  { id: 38,  licensePlate: 'EV-038', make: 'Honda',     model: 'Prologue',             year: 2024, driverId: 38,      colour: 'Blue',    range: 296 },
  { id: 39,  licensePlate: 'EV-039', make: 'Fisker',    model: 'Ocean',                year: 2023, driverId: 39,     colour: 'White',   range: 360 },
  { id: 40,  licensePlate: 'EV-040', make: 'Canoo',     model: 'Lifestyle Vehicle',    year: 2024, driverId: 40,      colour: 'Yellow',  range: 250 },
  { id: 41,  licensePlate: 'EV-041', make: 'Porsche',   model: 'Taycan',               year: 2023, driverId: 41,       colour: 'Silver',  range: 278 },
  { id: 42,  licensePlate: 'EV-042', make: 'Porsche',   model: 'Taycan Cross Turismo', year: 2024, driverId: 42,    colour: 'Black',   range: 267 },
  { id: 43,  licensePlate: 'EV-043', make: 'Jaguar',    model: 'I-PACE',               year: 2022, driverId: 43,      colour: 'Blue',    range: 246 },
  { id: 44,  licensePlate: 'EV-044', make: 'Jaguar',    model: 'I-PACE',               year: 2023, driverId: 44,      colour: 'Red',     range: 253 },
  { id: 45,  licensePlate: 'EV-045', make: 'Mazda',     model: 'MX-30',                year: 2023, driverId: 45,       colour: 'White',   range: 212 },
  { id: 46,  licensePlate: 'EV-046', make: 'Mazda',     model: 'MX-30',                year: 2024, driverId: 46,     colour: 'Grey',    range: 218 },
  { id: 47,  licensePlate: 'EV-047', make: 'Renault',   model: 'Zoe',                  year: 2022, driverId: 47,    colour: 'Orange',  range: 245 },
  { id: 48,  licensePlate: 'EV-048', make: 'Renault',   model: 'Megane E-Tech',        year: 2023, driverId: 48,   colour: 'White',   range: 292 },
  { id: 49,  licensePlate: 'EV-049', make: 'Renault',   model: 'Scenic E-Tech',        year: 2024, driverId: 49,         colour: 'Blue',    range: 379 },
  { id: 50,  licensePlate: 'EV-050', make: 'Citroën',   model: 'ë-C4',                 year: 2023, driverId: 50,    colour: 'Green',   range: 220 },
  { id: 51,  licensePlate: 'EV-051', make: 'Citroën',   model: 'ë-Berlingo',           year: 2022, driverId: 51,     colour: 'White',   range: 208 },
  { id: 52,  licensePlate: 'EV-052', make: 'BYD',       model: 'Atto 3',               year: 2023, driverId: 52,          colour: 'Silver',  range: 260 },
  { id: 53,  licensePlate: 'EV-053', make: 'BYD',       model: 'Han',                  year: 2024, driverId: 53,     colour: 'Black',   range: 401 },
  { id: 54,  licensePlate: 'EV-054', make: 'BYD',       model: 'Tang',                 year: 2023, driverId: 54,         colour: 'Blue',    range: 363 },
  { id: 55,  licensePlate: 'EV-055', make: 'BYD',       model: 'Seal',                 year: 2024, driverId: 55,    colour: 'Red',     range: 336 },
  { id: 56,  licensePlate: 'EV-056', make: 'Xpeng',     model: 'P7',                   year: 2023, driverId: 56,        colour: 'White',   range: 310 },
  { id: 57,  licensePlate: 'EV-057', make: 'Xpeng',     model: 'G9',                   year: 2024, driverId: 57,    colour: 'Grey',    range: 332 },
  { id: 58,  licensePlate: 'EV-058', make: 'Li Auto',   model: 'L9',                   year: 2023, driverId: 58,       colour: 'Black',   range: 388 },
  { id: 59,  licensePlate: 'EV-059', make: 'Li Auto',   model: 'L7',                   year: 2024, driverId: 59,       colour: 'Silver',  range: 372 },
  { id: 60,  licensePlate: 'EV-060', make: 'Genesis',   model: 'GV60',                 year: 2023, driverId: 60,     colour: 'White',   range: 248 },
  { id: 61,  licensePlate: 'EV-061', make: 'Genesis',   model: 'GV70 Electrified',     year: 2024, driverId: 61,          colour: 'Blue',    range: 236 },
  { id: 62,  licensePlate: 'EV-062', make: 'Genesis',   model: 'G80 Electrified',      year: 2023, driverId: 62,     colour: 'Grey',    range: 282 },
  { id: 63,  licensePlate: 'EV-063', make: 'Alfa Romeo',model: 'Tonale PHEV',          year: 2024, driverId: 63,     colour: 'Red',     range: 262 },
  { id: 64,  licensePlate: 'EV-064', make: 'Alfa Romeo',model: 'Junior Elettrica',     year: 2025, driverId: 64,      colour: 'White',   range: 249 },
  { id: 65,  licensePlate: 'EV-065', make: 'Fiat',      model: '500e',                 year: 2022, driverId: 65,      colour: 'Orange',  range: 200 },
  { id: 66,  licensePlate: 'EV-066', make: 'Fiat',      model: '500e',                 year: 2023, driverId: 66,          colour: 'Blue',    range: 207 },
  { id: 67,  licensePlate: 'EV-067', make: 'Mini',      model: 'Cooper SE',            year: 2022, driverId: 67,        colour: 'Yellow',  range: 200 },
  { id: 68,  licensePlate: 'EV-068', make: 'Mini',      model: 'Countryman E',         year: 2024, driverId: 68,   colour: 'Green',   range: 298 },
  { id: 69,  licensePlate: 'EV-069', make: 'Opel',      model: 'Corsa-e',              year: 2022, driverId: 69,       colour: 'White',   range: 209 },
  { id: 70,  licensePlate: 'EV-070', make: 'Opel',      model: 'Mokka-e',              year: 2023, driverId: 70,   colour: 'Black',   range: 222 },
  { id: 71,  licensePlate: 'EV-071', make: 'Tesla',     model: 'Model 3',              year: 2024, driverId: 71,         colour: 'Red',     range: 362 },
  { id: 72,  licensePlate: 'EV-072', make: 'Tesla',     model: 'Model Y',              year: 2025, driverId: 72, colour: 'White',   range: 338 },
  { id: 73,  licensePlate: 'EV-073', make: 'Tesla',     model: 'Cybertruck',           year: 2024, driverId: 73,            colour: 'Silver',  range: 340 },
  { id: 74,  licensePlate: 'EV-074', make: 'Rivian',    model: 'R2',                   year: 2025, driverId: 74,      colour: 'Blue',    range: 300 },
  { id: 75,  licensePlate: 'EV-075', make: 'Ford',      model: 'Explorer EV',          year: 2024, driverId: 75,       colour: 'Grey',    range: 303 },
  { id: 76,  licensePlate: 'EV-076', make: 'Hyundai',   model: 'IONIQ 6',              year: 2024, driverId: 76,          colour: 'Black',   range: 368 },
  { id: 77,  licensePlate: 'EV-077', make: 'Kia',       model: 'EV6',                  year: 2024, driverId: 77,        colour: 'White',   range: 315 },
  { id: 78,  licensePlate: 'EV-078', make: 'BMW',       model: 'iX3',                  year: 2023, driverId: 78,       colour: 'Silver',  range: 285 },
  { id: 79,  licensePlate: 'EV-079', make: 'BMW',       model: 'i5',                   year: 2024, driverId: 79,   colour: 'Blue',    range: 295 },
  { id: 80,  licensePlate: 'EV-080', make: 'Mercedes',  model: 'EQA',                  year: 2023, driverId: 80,      colour: 'Green',   range: 258 },
  { id: 81,  licensePlate: 'EV-081', make: 'Mercedes',  model: 'EQC',                  year: 2022, driverId: 81,        colour: 'White',   range: 260 },
  { id: 82,  licensePlate: 'EV-082', make: 'Audi',      model: 'e-tron GT',            year: 2023, driverId: 82,     colour: 'Red',     range: 293 },
  { id: 83,  licensePlate: 'EV-083', make: 'Volvo',     model: 'EX40',                 year: 2024, driverId: 83,     colour: 'Grey',    range: 270 },
  { id: 84,  licensePlate: 'EV-084', make: 'Polestar',  model: 'Polestar 4',           year: 2025, driverId: 84,       colour: 'Black',   range: 320 },
  { id: 85,  licensePlate: 'EV-085', make: 'Nio',       model: 'ES6',                  year: 2023, driverId: 85,       colour: 'White',   range: 360 },
  { id: 86,  licensePlate: 'EV-086', make: 'VW',        model: 'ID.3',                 year: 2022, driverId: 86,      colour: 'Blue',    range: 265 },
  { id: 87,  licensePlate: 'EV-087', make: 'VW',        model: 'ID.5',                 year: 2024, driverId: 87,      colour: 'Silver',  range: 310 },
  { id: 88,  licensePlate: 'EV-088', make: 'Porsche',   model: 'Macan EV',             year: 2024, driverId: 88,     colour: 'Orange',  range: 308 },
  { id: 89,  licensePlate: 'EV-089', make: 'Jaguar',    model: 'I-PACE',               year: 2025, driverId: 89,      colour: 'Black',   range: 250 },
  { id: 90,  licensePlate: 'EV-090', make: 'Genesis',   model: 'GV80 Electrified',     year: 2025, driverId: 90,      colour: 'White',   range: 290 },
  { id: 91,  licensePlate: 'EV-091', make: 'BYD',       model: 'Dolphin',              year: 2023, driverId: 91,      colour: 'Yellow',  range: 265 },
  { id: 92,  licensePlate: 'EV-092', make: 'BYD',       model: 'Seagull',              year: 2024, driverId: 92,      colour: 'Green',   range: 252 },
  { id: 93,  licensePlate: 'EV-093', make: 'Xpeng',     model: 'G6',                   year: 2024, driverId: 93,     colour: 'Blue',    range: 354 },
  { id: 94,  licensePlate: 'EV-094', make: 'Renault',   model: 'Twingo Electric',      year: 2025, driverId: 94,      colour: 'White',   range: 205 },
  { id: 95,  licensePlate: 'EV-095', make: 'Citroën',   model: 'ë-C4 X',               year: 2024, driverId: 95,    colour: 'Red',     range: 231 },
  { id: 96,  licensePlate: 'EV-096', make: 'Mini',      model: 'Aceman E',             year: 2025, driverId: 96,       colour: 'Orange',  range: 252 },
  { id: 97,  licensePlate: 'EV-097', make: 'Opel',      model: 'Astra-e',              year: 2024, driverId: 97,     colour: 'Grey',    range: 257 },
  { id: 98,  licensePlate: 'EV-098', make: 'Nissan',    model: 'Ariya',                year: 2024, driverId: 98,       colour: 'White',   range: 304 },
  { id: 99,  licensePlate: 'EV-099', make: 'Toyota',    model: 'bZ3',                  year: 2024, driverId: 99,      colour: 'Silver',  range: 301 },
  { id: 100, licensePlate: 'EV-100', make: 'Mazda',     model: 'EZ-6',                 year: 2025, driverId: 100,     colour: 'Black',   range: 375 },
  { id: 101, licensePlate: 'EV-101', make: 'Tesla',     model: 'Model S',              year: 2024, driverId: null,         colour: 'White',   range: 412 },
  { id: 102, licensePlate: 'EV-102', make: 'Tesla',     model: 'Model X',              year: 2025, driverId: null,         colour: 'Blue',    range: 351 },
  { id: 103, licensePlate: 'EV-103', make: 'Lucid',     model: 'Air Sapphire',         year: 2024, driverId: null,         colour: 'Silver',  range: 427 },
  { id: 104, licensePlate: 'EV-104', make: 'Rivian',    model: 'R1T',                  year: 2024, driverId: null,         colour: 'Green',   range: 320 },
  { id: 105, licensePlate: 'EV-105', make: 'Ford',      model: 'Mustang Mach-E',       year: 2024, driverId: null,         colour: 'Red',     range: 318 },
  { id: 106, licensePlate: 'EV-106', make: 'Chevy',     model: 'Equinox EV',           year: 2024, driverId: null,         colour: 'White',   range: 319 },
  { id: 107, licensePlate: 'EV-107', make: 'Chevy',     model: 'Blazer EV',            year: 2023, driverId: null,         colour: 'Black',   range: 324 },
  { id: 108, licensePlate: 'EV-108', make: 'Hyundai',   model: 'IONIQ 5',              year: 2024, driverId: null,         colour: 'Grey',    range: 310 },
  { id: 109, licensePlate: 'EV-109', make: 'Kia',       model: 'EV3',                  year: 2025, driverId: null,         colour: 'Blue',    range: 373 },
  { id: 110, licensePlate: 'EV-110', make: 'BMW',       model: 'iX1',                  year: 2024, driverId: null,         colour: 'Orange',  range: 272 },
  { id: 111, licensePlate: 'EV-111', make: 'Mercedes',  model: 'EQE',                  year: 2024, driverId: null,         colour: 'White',   range: 348 },
  { id: 112, licensePlate: 'EV-112', make: 'Audi',      model: 'Q4 e-tron',            year: 2023, driverId: null,         colour: 'Silver',  range: 265 },
  { id: 113, licensePlate: 'EV-113', make: 'Volvo',     model: 'EX30',                 year: 2024, driverId: null,         colour: 'Green',   range: 296 },
  { id: 114, licensePlate: 'EV-114', make: 'Polestar',  model: 'Polestar 2',           year: 2025, driverId: null,         colour: 'Black',   range: 278 },
  { id: 115, licensePlate: 'EV-115', make: 'Nio',       model: 'EL7',                  year: 2024, driverId: null,         colour: 'White',   range: 358 },
  { id: 116, licensePlate: 'EV-116', make: 'VW',        model: 'ID.7',                 year: 2024, driverId: null,         colour: 'Blue',    range: 386 },
  { id: 117, licensePlate: 'EV-117', make: 'GMC',       model: 'Sierra EV',            year: 2024, driverId: null,         colour: 'Red',     range: 400 },
  { id: 118, licensePlate: 'EV-118', make: 'Cadillac',  model: 'OPTIQ',                year: 2025, driverId: null,         colour: 'White',   range: 300 },
  { id: 119, licensePlate: 'EV-119', make: 'Honda',     model: 'e:Ny1',                year: 2024, driverId: null,         colour: 'Silver',  range: 258 },
  { id: 120, licensePlate: 'EV-120', make: 'Subaru',    model: 'Solterra',             year: 2024, driverId: null,         colour: 'Grey',    range: 228 },
  { id: 121, licensePlate: 'EV-121', make: 'Porsche',   model: 'Taycan',               year: 2025, driverId: null,         colour: 'Yellow',  range: 282 },
  { id: 122, licensePlate: 'EV-122', make: 'BYD',       model: 'Atto 3',               year: 2024, driverId: null,         colour: 'Blue',    range: 268 },
  { id: 123, licensePlate: 'EV-123', make: 'Genesis',   model: 'GV60',                 year: 2024, driverId: null,         colour: 'White',   range: 253 },
  { id: 124, licensePlate: 'EV-124', make: 'Renault',   model: 'Megane E-Tech',        year: 2024, driverId: null,         colour: 'Black',   range: 298 },
  { id: 125, licensePlate: 'EV-125', make: 'Xpeng',     model: 'X9',                   year: 2024, driverId: null,         colour: 'Silver',  range: 420 },
  { id: 126, licensePlate: 'EV-126', make: 'Li Auto',   model: 'L6',                   year: 2024, driverId: null,         colour: 'Green',   range: 342 },
  { id: 127, licensePlate: 'EV-127', make: 'Alfa Romeo',model: 'Junior Elettrica',     year: 2024, driverId: null,         colour: 'Red',     range: 255 },
  { id: 128, licensePlate: 'EV-128', make: 'Fiat',      model: '600e',                 year: 2024, driverId: null,         colour: 'White',   range: 249 },
  { id: 129, licensePlate: 'EV-129', make: 'Mini',      model: 'Cooper SE',            year: 2024, driverId: null,         colour: 'Orange',  range: 212 },
  { id: 130, licensePlate: 'EV-130', make: 'Opel',      model: 'Grandland-e',          year: 2024, driverId: null,         colour: 'Grey',    range: 281 },
  { id: 131, licensePlate: 'EV-131', make: 'Tesla',     model: 'Model 3',              year: 2025, driverId: null,         colour: 'White',   range: 370 },
  { id: 132, licensePlate: 'EV-132', make: 'Nissan',    model: 'Leaf',                 year: 2024, driverId: null,         colour: 'Blue',    range: 226 },
  { id: 133, licensePlate: 'EV-133', make: 'Toyota',    model: 'bZ4X',                 year: 2024, driverId: null,         colour: 'Silver',  range: 259 },
  { id: 134, licensePlate: 'EV-134', make: 'Mazda',     model: 'MX-30 R-EV',           year: 2024, driverId: null,         colour: 'Black',   range: 340 },
  { id: 135, licensePlate: 'EV-135', make: 'Ford',      model: 'F-150 Lightning',      year: 2024, driverId: null,         colour: 'Red',     range: 325 },
  { id: 136, licensePlate: 'EV-136', make: 'Rivian',    model: 'R1S',                  year: 2025, driverId: null,         colour: 'Green',   range: 328 },
  { id: 137, licensePlate: 'EV-137', make: 'Hyundai',   model: 'IONIQ 9',              year: 2025, driverId: null,         colour: 'White',   range: 345 },
  { id: 138, licensePlate: 'EV-138', make: 'Kia',       model: 'EV9',                  year: 2025, driverId: null,         colour: 'Grey',    range: 308 },
  { id: 139, licensePlate: 'EV-139', make: 'BMW',       model: 'i7',                   year: 2024, driverId: null,         colour: 'Black',   range: 321 },
  { id: 140, licensePlate: 'EV-140', make: 'Mercedes',  model: 'EQS SUV',              year: 2024, driverId: null,         colour: 'Blue',    range: 305 },
  { id: 141, licensePlate: 'EV-141', make: 'Audi',      model: 'Q6 e-tron',            year: 2024, driverId: null,         colour: 'White',   range: 387 },
  { id: 142, licensePlate: 'EV-142', make: 'Volvo',     model: 'EC40',                 year: 2024, driverId: null,         colour: 'Red',     range: 274 },
  { id: 143, licensePlate: 'EV-143', make: 'Polestar',  model: 'Polestar 3',           year: 2025, driverId: null,         colour: 'Silver',  range: 318 },
  { id: 144, licensePlate: 'EV-144', make: 'Nio',       model: 'EC6',                  year: 2024, driverId: null,         colour: 'Yellow',  range: 375 },
  { id: 145, licensePlate: 'EV-145', make: 'VW',        model: 'ID.4',                 year: 2025, driverId: null,         colour: 'Blue',    range: 281 },
  { id: 146, licensePlate: 'EV-146', make: 'Porsche',   model: 'Macan EV',             year: 2025, driverId: null,         colour: 'White',   range: 314 },
  { id: 147, licensePlate: 'EV-147', make: 'Jaguar',    model: 'I-PACE',               year: 2024, driverId: null,         colour: 'Black',   range: 259 },
  { id: 148, licensePlate: 'EV-148', make: 'BYD',       model: 'Sea Lion 6',           year: 2024, driverId: null,         colour: 'Green',   range: 335 },
  { id: 149, licensePlate: 'EV-149', make: 'Genesis',   model: 'GV70 Electrified',     year: 2025, driverId: null,         colour: 'Grey',    range: 240 },
  { id: 150, licensePlate: 'EV-150', make: 'Renault',   model: 'Scenic E-Tech',        year: 2025, driverId: null,         colour: 'Orange',  range: 385 },
  { id: 151, licensePlate: 'EV-151', make: 'Citroën',   model: 'ë-C4',                 year: 2024, driverId: null,         colour: 'White',   range: 227 },
  { id: 152, licensePlate: 'EV-152', make: 'Xpeng',     model: 'P7',                   year: 2025, driverId: null,         colour: 'Blue',    range: 316 },
  { id: 153, licensePlate: 'EV-153', make: 'Li Auto',   model: 'L9',                   year: 2025, driverId: null,         colour: 'Silver',  range: 394 },
  { id: 154, licensePlate: 'EV-154', make: 'Alfa Romeo',model: 'Tonale PHEV',          year: 2025, driverId: null,         colour: 'Red',     range: 270 },
  { id: 155, licensePlate: 'EV-155', make: 'Mini',      model: 'Countryman E',         year: 2025, driverId: null,         colour: 'White',   range: 305 },
  { id: 156, licensePlate: 'EV-156', make: 'Opel',      model: 'Corsa-e',              year: 2024, driverId: null,         colour: 'Black',   range: 216 },
  { id: 157, licensePlate: 'EV-157', make: 'Chevy',     model: 'Equinox EV',           year: 2025, driverId: null,         colour: 'Blue',    range: 322 },
  { id: 158, licensePlate: 'EV-158', make: 'Honda',     model: 'Prologue',             year: 2025, driverId: null,         colour: 'Grey',    range: 299 },
  { id: 159, licensePlate: 'EV-159', make: 'Subaru',    model: 'Trailseeker EV',       year: 2025, driverId: null,         colour: 'Silver',  range: 260 },
  { id: 160, licensePlate: 'EV-160', make: 'Toyota',    model: 'bZ3C',                 year: 2025, driverId: null,         colour: 'White',   range: 288 },
  { id: 161, licensePlate: 'EV-161', make: 'Nissan',    model: 'Ariya',                year: 2025, driverId: null,         colour: 'Green',   range: 310 },
  { id: 162, licensePlate: 'EV-162', make: 'GMC',       model: 'Hummer EV',            year: 2024, driverId: null,         colour: 'Black',   range: 334 },
  { id: 163, licensePlate: 'EV-163', make: 'Cadillac',  model: 'LYRIQ',                year: 2025, driverId: null,         colour: 'Red',     range: 319 },
  { id: 164, licensePlate: 'EV-164', make: 'Fisker',    model: 'PEAR',                 year: 2025, driverId: null,         colour: 'Orange',  range: 305 },
  { id: 165, licensePlate: 'EV-165', make: 'Mazda',     model: 'EZ-6',                 year: 2024, driverId: null,         colour: 'White',   range: 382 },
  { id: 166, licensePlate: 'EV-166', make: 'Tesla',     model: 'Cybertruck',           year: 2025, driverId: null,         colour: 'Silver',  range: 347 },
  { id: 167, licensePlate: 'EV-167', make: 'Lucid',     model: 'Gravity',              year: 2025, driverId: null,         colour: 'White',   range: 440 },
  { id: 168, licensePlate: 'EV-168', make: 'Rivian',    model: 'R2',                   year: 2024, driverId: null,         colour: 'Blue',    range: 296 },
  { id: 169, licensePlate: 'EV-169', make: 'Ford',      model: 'Explorer EV',          year: 2025, driverId: null,         colour: 'Grey',    range: 308 },
  { id: 170, licensePlate: 'EV-170', make: 'Hyundai',   model: 'IONIQ 5',              year: 2025, driverId: null,         colour: 'Red',     range: 317 },
  { id: 171, licensePlate: 'EV-171', make: 'Kia',       model: 'EV6',                  year: 2025, driverId: null,         colour: 'White',   range: 321 },
  { id: 172, licensePlate: 'EV-172', make: 'BMW',       model: 'i4',                   year: 2025, driverId: null,         colour: 'Black',   range: 307 },
  { id: 173, licensePlate: 'EV-173', make: 'Mercedes',  model: 'EQE',                  year: 2025, driverId: null,         colour: 'Blue',    range: 356 },
  { id: 174, licensePlate: 'EV-174', make: 'Audi',      model: 'A6 e-tron',            year: 2025, driverId: null,         colour: 'Silver',  range: 375 },
  { id: 175, licensePlate: 'EV-175', make: 'Volvo',     model: 'EX90',                 year: 2025, driverId: null,         colour: 'Green',   range: 303 },
  { id: 176, licensePlate: 'EV-176', make: 'Polestar',  model: 'Polestar 4',           year: 2024, driverId: null,         colour: 'White',   range: 325 },
  { id: 177, licensePlate: 'EV-177', make: 'BYD',       model: 'Han',                  year: 2025, driverId: null,         colour: 'Red',     range: 408 },
  { id: 178, licensePlate: 'EV-178', make: 'Xpeng',     model: 'G9',                   year: 2025, driverId: null,         colour: 'Black',   range: 338 },
  { id: 179, licensePlate: 'EV-179', make: 'Li Auto',   model: 'L7',                   year: 2025, driverId: null,         colour: 'Grey',    range: 378 },
  { id: 180, licensePlate: 'EV-180', make: 'Genesis',   model: 'GV80 Electrified',     year: 2024, driverId: null,         colour: 'White',   range: 294 },
  { id: 181, licensePlate: 'EV-181', make: 'Nio',       model: 'ET5',                  year: 2025, driverId: null,         colour: 'Blue',    range: 335 },
  { id: 182, licensePlate: 'EV-182', make: 'VW',        model: 'ID.7',                 year: 2025, driverId: null,         colour: 'Silver',  range: 390 },
  { id: 183, licensePlate: 'EV-183', make: 'Porsche',   model: 'Taycan Cross Turismo', year: 2025, driverId: null,         colour: 'Black',   range: 272 },
  { id: 184, licensePlate: 'EV-184', make: 'Renault',   model: 'Zoe',                  year: 2024, driverId: null,         colour: 'Yellow',  range: 250 },
  { id: 185, licensePlate: 'EV-185', make: 'Citroën',   model: 'ë-Berlingo',           year: 2024, driverId: null,         colour: 'White',   range: 214 },
  { id: 186, licensePlate: 'EV-186', make: 'Fiat',      model: '600e',                 year: 2025, driverId: null,         colour: 'Orange',  range: 254 },
  { id: 187, licensePlate: 'EV-187', make: 'Mini',      model: 'Aceman E',             year: 2024, driverId: null,         colour: 'Blue',    range: 257 },
  { id: 188, licensePlate: 'EV-188', make: 'Opel',      model: 'Astra-e',              year: 2025, driverId: null,         colour: 'Grey',    range: 261 },
  { id: 189, licensePlate: 'EV-189', make: 'Alfa Romeo',model: 'Junior Elettrica',     year: 2023, driverId: null,         colour: 'Red',     range: 245 },
  { id: 190, licensePlate: 'EV-190', make: 'Mazda',     model: 'MX-30',                year: 2025, driverId: null,         colour: 'White',   range: 220 },
  { id: 191, licensePlate: 'EV-191', make: 'Tesla',     model: 'Model Y',              year: 2022, driverId: null,         colour: 'Silver',  range: 326 },
  { id: 192, licensePlate: 'EV-192', make: 'Rivian',    model: 'R1T',                  year: 2025, driverId: null,         colour: 'Green',   range: 316 },
  { id: 193, licensePlate: 'EV-193', make: 'Hyundai',   model: 'IONIQ 6',              year: 2025, driverId: null,         colour: 'Black',   range: 374 },
  { id: 194, licensePlate: 'EV-194', make: 'Kia',       model: 'EV9',                  year: 2022, driverId: null,         colour: 'Blue',    range: 298 },
  { id: 195, licensePlate: 'EV-195', make: 'BMW',       model: 'iX',                   year: 2025, driverId: null,         colour: 'White',   range: 330 },
  { id: 196, licensePlate: 'EV-196', make: 'Mercedes',  model: 'EQA',                  year: 2024, driverId: null,         colour: 'Grey',    range: 264 },
  { id: 197, licensePlate: 'EV-197', make: 'Audi',      model: 'Q8 e-tron',            year: 2025, driverId: null,         colour: 'Red',     range: 291 },
  { id: 198, licensePlate: 'EV-198', make: 'Volvo',     model: 'EX40',                 year: 2025, driverId: null,         colour: 'Silver',  range: 275 },
  { id: 199, licensePlate: 'EV-199', make: 'Nio',       model: 'ET7',                  year: 2025, driverId: null,         colour: 'White',   range: 380 },
  { id: 200, licensePlate: 'EV-200', make: 'BYD',       model: 'Seal',                 year: 2025, driverId: null,         colour: 'Blue',    range: 341 },
  { id: 201, licensePlate: 'EV-201', make: 'Chevy',     model: 'Blazer EV',            year: 2024, driverId: null,         colour: 'Black',   range: 328 },
  { id: 202, licensePlate: 'EV-202', make: 'Ford',      model: 'F-150 Lightning',      year: 2025, driverId: null,         colour: 'White',   range: 330 },
  { id: 203, licensePlate: 'EV-203', make: 'Toyota',    model: 'bZ4X',                 year: 2025, driverId: null,         colour: 'Green',   range: 262 },
  { id: 204, licensePlate: 'EV-204', make: 'Nissan',    model: 'Ariya',                year: 2022, driverId: null,         colour: 'Red',     range: 284 },
  { id: 205, licensePlate: 'EV-205', make: 'GMC',       model: 'Sierra EV',            year: 2025, driverId: null,         colour: 'Silver',  range: 410 },
  { id: 206, licensePlate: 'EV-206', make: 'Cadillac',  model: 'CELESTIQ',             year: 2025, driverId: null,         colour: 'Black',   range: 300 },
  { id: 207, licensePlate: 'EV-207', make: 'Honda',     model: 'e:Ny1',                year: 2024, driverId: null,         colour: 'Blue',    range: 263 },
  { id: 208, licensePlate: 'EV-208', make: 'Subaru',    model: 'Solterra',             year: 2025, driverId: null,         colour: 'White',   range: 232 },
  { id: 209, licensePlate: 'EV-209', make: 'Jaguar',    model: 'I-PACE',               year: 2025, driverId: null,         colour: 'Grey',    range: 254 },
  { id: 210, licensePlate: 'EV-210', make: 'Genesis',   model: 'GV60',                 year: 2025, driverId: null,         colour: 'Orange',  range: 256 },
  { id: 211, licensePlate: 'EV-211', make: 'Porsche',   model: 'Taycan',               year: 2022, driverId: null,         colour: 'White',   range: 269 },
  { id: 212, licensePlate: 'EV-212', make: 'Xpeng',     model: 'G6',                   year: 2025, driverId: null,         colour: 'Blue',    range: 360 },
  { id: 213, licensePlate: 'EV-213', make: 'Renault',   model: 'Megane E-Tech',        year: 2025, driverId: null,         colour: 'Silver',  range: 303 },
  { id: 214, licensePlate: 'EV-214', make: 'Li Auto',   model: 'L6',                   year: 2025, driverId: null,         colour: 'Red',     range: 348 },
  { id: 215, licensePlate: 'EV-215', make: 'Alfa Romeo',model: 'Tonale PHEV',          year: 2022, driverId: null,         colour: 'White',   range: 255 },
  { id: 216, licensePlate: 'EV-216', make: 'Fiat',      model: '500e',                 year: 2024, driverId: null,         colour: 'Yellow',  range: 211 },
  { id: 217, licensePlate: 'EV-217', make: 'Mini',      model: 'Cooper SE',            year: 2025, driverId: null,         colour: 'Black',   range: 204 },
  { id: 218, licensePlate: 'EV-218', make: 'Opel',      model: 'Mokka-e',              year: 2025, driverId: null,         colour: 'Green',   range: 226 },
  { id: 219, licensePlate: 'EV-219', make: 'Mazda',     model: 'MX-30 R-EV',           year: 2025, driverId: null,         colour: 'White',   range: 345 },
  { id: 220, licensePlate: 'EV-220', make: 'Tesla',     model: 'Model 3',              year: 2022, driverId: null,         colour: 'Blue',    range: 353 },
  { id: 221, licensePlate: 'EV-221', make: 'Rivian',    model: 'R1S',                  year: 2022, driverId: null,         colour: 'Grey',    range: 316 },
  { id: 222, licensePlate: 'EV-222', make: 'Hyundai',   model: 'IONIQ 5',              year: 2022, driverId: null,         colour: 'White',   range: 298 },
  { id: 223, licensePlate: 'EV-223', make: 'BMW',       model: 'iX3',                  year: 2024, driverId: null,         colour: 'Silver',  range: 289 },
  { id: 224, licensePlate: 'EV-224', make: 'Mercedes',  model: 'EQC',                  year: 2024, driverId: null,         colour: 'Black',   range: 265 },
  { id: 225, licensePlate: 'EV-225', make: 'Audi',      model: 'e-tron GT',            year: 2024, driverId: null,         colour: 'Red',     range: 298 },
  { id: 226, licensePlate: 'EV-226', make: 'Volvo',     model: 'EX30',                 year: 2023, driverId: null,         colour: 'Blue',    range: 291 },
  { id: 227, licensePlate: 'EV-227', make: 'Polestar',  model: 'Polestar 2',           year: 2023, driverId: null,         colour: 'White',   range: 265 },
  { id: 228, licensePlate: 'EV-228', make: 'BYD',       model: 'Dolphin',              year: 2024, driverId: null,         colour: 'Yellow',  range: 270 },
  { id: 229, licensePlate: 'EV-229', make: 'VW',        model: 'ID.3',                 year: 2024, driverId: null,         colour: 'Grey',    range: 272 },
  { id: 230, licensePlate: 'EV-230', make: 'Chevy',     model: 'Silverado EV',         year: 2025, driverId: null,         colour: 'White',   range: 408 },
  { id: 231, licensePlate: 'EV-231', make: 'Kia',       model: 'EV3',                  year: 2024, driverId: null,         colour: 'Blue',    range: 368 },
  { id: 232, licensePlate: 'EV-232', make: 'Ford',      model: 'Mustang Mach-E',       year: 2025, driverId: null,         colour: 'Red',     range: 322 },
  { id: 233, licensePlate: 'EV-233', make: 'Tesla',     model: 'Model S',              year: 2025, driverId: null,         colour: 'Silver',  range: 418 },
  { id: 234, licensePlate: 'EV-234', make: 'Lucid',     model: 'Air Grand Touring',    year: 2025, driverId: null,         colour: 'White',   range: 520 },
  { id: 235, licensePlate: 'EV-235', make: 'Genesis',   model: 'G80 Electrified',      year: 2025, driverId: null,         colour: 'Black',   range: 286 },
  { id: 236, licensePlate: 'EV-236', make: 'Nio',       model: 'ES6',                  year: 2025, driverId: null,         colour: 'Green',   range: 365 },
  { id: 237, licensePlate: 'EV-237', make: 'Renault',   model: 'Twingo Electric',      year: 2024, driverId: null,         colour: 'White',   range: 208 },
  { id: 238, licensePlate: 'EV-238', make: 'Citroën',   model: 'ë-C4 X',               year: 2025, driverId: null,         colour: 'Blue',    range: 237 },
  { id: 239, licensePlate: 'EV-239', make: 'Alfa Romeo',model: 'Junior Elettrica',     year: 2025, driverId: null,         colour: 'Orange',  range: 253 },
  { id: 240, licensePlate: 'EV-240', make: 'Mazda',     model: 'EZ-6',                 year: 2025, driverId: null,         colour: 'Silver',  range: 380 },
  { id: 241, licensePlate: 'EV-241', make: 'Mini',      model: 'Countryman E',         year: 2022, driverId: null,         colour: 'White',   range: 294 },
  { id: 242, licensePlate: 'EV-242', make: 'Opel',      model: 'Grandland-e',          year: 2025, driverId: null,         colour: 'Grey',    range: 283 },
  { id: 243, licensePlate: 'EV-243', make: 'Subaru',    model: 'Trailseeker EV',       year: 2024, driverId: null,         colour: 'Black',   range: 256 },
  { id: 244, licensePlate: 'EV-244', make: 'Toyota',    model: 'bZ3',                  year: 2023, driverId: null,         colour: 'Blue',    range: 298 },
  { id: 245, licensePlate: 'EV-245', make: 'Jaguar',    model: 'I-PACE',               year: 2022, driverId: null,         colour: 'White',   range: 243 },
  { id: 246, licensePlate: 'EV-246', make: 'Porsche',   model: 'Taycan',               year: 2024, driverId: null,         colour: 'Red',     range: 276 },
  { id: 247, licensePlate: 'EV-247', make: 'Xpeng',     model: 'X9',                   year: 2025, driverId: null,         colour: 'Silver',  range: 424 },
  { id: 248, licensePlate: 'EV-248', make: 'BYD',       model: 'Sea Lion 6',           year: 2025, driverId: null,         colour: 'White',   range: 340 },
  { id: 249, licensePlate: 'EV-249', make: 'Li Auto',   model: 'L9',                   year: 2022, driverId: null,         colour: 'Black',   range: 384 },
  { id: 250, licensePlate: 'EV-250', make: 'Rivian',    model: 'R2',                   year: 2023, driverId: null,         colour: 'Green',   range: 293 },
  { id: 251, licensePlate: 'EV-251', make: 'Tesla',     model: 'Model X',              year: 2022, driverId: null,         colour: 'Blue',    range: 340 },
  { id: 252, licensePlate: 'EV-252', make: 'Hyundai',   model: 'IONIQ 6',              year: 2022, driverId: null,         colour: 'White',   range: 355 },
  { id: 253, licensePlate: 'EV-253', make: 'BMW',       model: 'i5',                   year: 2025, driverId: null,         colour: 'Grey',    range: 299 },
  { id: 254, licensePlate: 'EV-254', make: 'Mercedes',  model: 'EQB',                  year: 2025, driverId: null,         colour: 'White',   range: 250 },
  { id: 255, licensePlate: 'EV-255', make: 'Audi',      model: 'Q4 e-tron',            year: 2024, driverId: null,         colour: 'Orange',  range: 268 },
  { id: 256, licensePlate: 'EV-256', make: 'Volvo',     model: 'EC40',                 year: 2023, driverId: null,         colour: 'Blue',    range: 271 },
  { id: 257, licensePlate: 'EV-257', make: 'Polestar',  model: 'Polestar 3',           year: 2022, driverId: null,         colour: 'Black',   range: 312 },
  { id: 258, licensePlate: 'EV-258', make: 'Nio',       model: 'EL7',                  year: 2025, driverId: null,         colour: 'Silver',  range: 362 },
  { id: 259, licensePlate: 'EV-259', make: 'VW',        model: 'ID.5',                 year: 2025, driverId: null,         colour: 'White',   range: 315 },
  { id: 260, licensePlate: 'EV-260', make: 'GMC',       model: 'Hummer EV',            year: 2025, driverId: null,         colour: 'Yellow',  range: 337 },
  { id: 261, licensePlate: 'EV-261', make: 'Cadillac',  model: 'OPTIQ',                year: 2024, driverId: null,         colour: 'Red',     range: 302 },
  { id: 262, licensePlate: 'EV-262', make: 'Honda',     model: 'Prologue',             year: 2022, driverId: null,         colour: 'White',   range: 292 },
  { id: 263, licensePlate: 'EV-263', make: 'Fisker',    model: 'Ocean',                year: 2024, driverId: null,         colour: 'Blue',    range: 366 },
  { id: 264, licensePlate: 'EV-264', make: 'Canoo',     model: 'Lifestyle Vehicle',    year: 2025, driverId: null,         colour: 'Green',   range: 253 },
  { id: 265, licensePlate: 'EV-265', make: 'Genesis',   model: 'GV70 Electrified',     year: 2022, driverId: null,         colour: 'Grey',    range: 234 },
  { id: 266, licensePlate: 'EV-266', make: 'Renault',   model: 'Scenic E-Tech',        year: 2022, driverId: null,         colour: 'White',   range: 376 },
  { id: 267, licensePlate: 'EV-267', make: 'BYD',       model: 'Atto 3',               year: 2025, driverId: null,         colour: 'Black',   range: 272 },
  { id: 268, licensePlate: 'EV-268', make: 'Xpeng',     model: 'G6',                   year: 2023, driverId: null,         colour: 'Blue',    range: 350 },
  { id: 269, licensePlate: 'EV-269', make: 'Li Auto',   model: 'L7',                   year: 2023, driverId: null,         colour: 'Silver',  range: 371 },
  { id: 270, licensePlate: 'EV-270', make: 'Alfa Romeo',model: 'Tonale PHEV',          year: 2023, driverId: null,         colour: 'Red',     range: 261 },
  { id: 271, licensePlate: 'EV-271', make: 'Mini',      model: 'Aceman E',             year: 2023, driverId: null,         colour: 'White',   range: 253 },
  { id: 272, licensePlate: 'EV-272', make: 'Opel',      model: 'Corsa-e',              year: 2025, driverId: null,         colour: 'Orange',  range: 211 },
  { id: 273, licensePlate: 'EV-273', make: 'Mazda',     model: 'MX-30',                year: 2022, driverId: null,         colour: 'Grey',    range: 209 },
  { id: 274, licensePlate: 'EV-274', make: 'Nissan',    model: 'Leaf',                 year: 2025, driverId: null,         colour: 'White',   range: 228 },
  { id: 275, licensePlate: 'EV-275', make: 'Toyota',    model: 'bZ3C',                 year: 2024, driverId: null,         colour: 'Blue',    range: 285 },
  { id: 276, licensePlate: 'EV-276', make: 'Chevy',     model: 'Bolt EV',              year: 2024, driverId: null,         colour: 'Yellow',  range: 264 },
  { id: 277, licensePlate: 'EV-277', make: 'Ford',      model: 'Explorer EV',          year: 2022, driverId: null,         colour: 'Silver',  range: 299 },
  { id: 278, licensePlate: 'EV-278', make: 'Rivian',    model: 'R1T',                  year: 2022, driverId: null,         colour: 'Black',   range: 308 },
  { id: 279, licensePlate: 'EV-279', make: 'Hyundai',   model: 'IONIQ 9',              year: 2024, driverId: null,         colour: 'White',   range: 342 },
  { id: 280, licensePlate: 'EV-280', make: 'Kia',       model: 'EV3',                  year: 2023, driverId: null,         colour: 'Green',   range: 369 },
  { id: 281, licensePlate: 'EV-281', make: 'BMW',       model: 'iX1',                  year: 2025, driverId: null,         colour: 'Blue',    range: 276 },
  { id: 282, licensePlate: 'EV-282', make: 'Mercedes',  model: 'EQS',                  year: 2025, driverId: null,         colour: 'White',   range: 355 },
  { id: 283, licensePlate: 'EV-283', make: 'Audi',      model: 'Q6 e-tron',            year: 2025, driverId: null,         colour: 'Red',     range: 390 },
  { id: 284, licensePlate: 'EV-284', make: 'Volvo',     model: 'EX30',                 year: 2025, driverId: null,         colour: 'Grey',    range: 297 },
  { id: 285, licensePlate: 'EV-285', make: 'Polestar',  model: 'Polestar 4',           year: 2023, driverId: null,         colour: 'Black',   range: 321 },
  { id: 286, licensePlate: 'EV-286', make: 'Nio',       model: 'EC6',                  year: 2025, driverId: null,         colour: 'Silver',  range: 378 },
  { id: 287, licensePlate: 'EV-287', make: 'VW',        model: 'ID.Buzz',              year: 2025, driverId: null,         colour: 'Orange',  range: 235 },
  { id: 288, licensePlate: 'EV-288', make: 'Porsche',   model: 'Taycan Cross Turismo', year: 2023, driverId: null,         colour: 'White',   range: 264 },
  { id: 289, licensePlate: 'EV-289', make: 'BYD',       model: 'Tang',                 year: 2025, driverId: null,         colour: 'Blue',    range: 368 },
  { id: 290, licensePlate: 'EV-290', make: 'Xpeng',     model: 'P7',                   year: 2024, driverId: null,         colour: 'Black',   range: 312 },
  { id: 291, licensePlate: 'EV-291', make: 'Genesis',   model: 'GV60',                 year: 2022, driverId: null,         colour: 'White',   range: 244 },
  { id: 292, licensePlate: 'EV-292', make: 'Renault',   model: 'Zoe',                  year: 2025, driverId: null,         colour: 'Yellow',  range: 248 },
  { id: 293, licensePlate: 'EV-293', make: 'Citroën',   model: 'ë-C4',                 year: 2025, driverId: null,         colour: 'Green',   range: 225 },
  { id: 294, licensePlate: 'EV-294', make: 'Fiat',      model: '500e',                 year: 2025, driverId: null,         colour: 'White',   range: 213 },
  { id: 295, licensePlate: 'EV-295', make: 'Mini',      model: 'Cooper SE',            year: 2023, driverId: null,         colour: 'Blue',    range: 206 },
  { id: 296, licensePlate: 'EV-296', make: 'Opel',      model: 'Mokka-e',              year: 2024, driverId: null,         colour: 'Red',     range: 225 },
  { id: 297, licensePlate: 'EV-297', make: 'Mazda',     model: 'MX-30 R-EV',           year: 2023, driverId: null,         colour: 'Silver',  range: 338 },
  { id: 298, licensePlate: 'EV-298', make: 'Alfa Romeo',model: 'Junior Elettrica',     year: 2022, driverId: null,         colour: 'Black',   range: 243 },
  { id: 299, licensePlate: 'EV-299', make: 'Jeep',      model: 'Recon EV',             year: 2025, driverId: null,         colour: 'White',   range: 350 },
  { id: 300, licensePlate: 'EV-300', make: 'Lucid',     model: 'Gravity',              year: 2024, driverId: null,         colour: 'Blue',    range: 450 },
]
