export const vehicles = [
  { id: 1,  licensePlate: 'EV-001', make: 'Tesla',    model: 'Model 3',         year: 2023, driver: 'James Okafor',    colour: 'White',   range: 358 },
  { id: 2,  licensePlate: 'EV-002', make: 'Tesla',    model: 'Model Y',         year: 2024, driver: 'Priya Nair',      colour: 'Black',   range: 330 },
  { id: 3,  licensePlate: 'EV-003', make: 'Tesla',    model: 'Model S',         year: 2022, driver: 'Carlos Mendes',   colour: 'Red',     range: 405 },
  { id: 4,  licensePlate: 'EV-004', make: 'Tesla',    model: 'Model X',         year: 2023, driver: 'Amara Diallo',    colour: 'Silver',  range: 348 },
  { id: 5,  licensePlate: 'EV-005', make: 'Rivian',   model: 'R1T',             year: 2023, driver: 'Sophie Larsson',  colour: 'Green',   range: 314 },
  { id: 6,  licensePlate: 'EV-006', make: 'Rivian',   model: 'R1S',             year: 2024, driver: 'Daniel Park',     colour: 'Blue',    range: 321 },
  { id: 7,  licensePlate: 'EV-007', make: 'Ford',     model: 'F-150 Lightning', year: 2023, driver: 'Fatima Al-Rashid',colour: 'Grey',    range: 320 },
  { id: 8,  licensePlate: 'EV-008', make: 'Ford',     model: 'Mustang Mach-E',  year: 2022, driver: 'Luca Rossi',      colour: 'White',   range: 312 },
  { id: 9,  licensePlate: 'EV-009', make: 'Chevy',    model: 'Bolt EV',         year: 2023, driver: 'Yuki Tanaka',     colour: 'Yellow',  range: 259 },
  { id: 10, licensePlate: 'EV-010', make: 'Chevy',    model: 'Silverado EV',    year: 2024, driver: 'Marcus Webb',     colour: 'Black',   range: 400 },
  { id: 11, licensePlate: 'EV-011', make: 'Hyundai',  model: 'IONIQ 6',         year: 2023, driver: 'Ingrid Holm',     colour: 'Blue',    range: 361 },
  { id: 12, licensePlate: 'EV-012', make: 'Hyundai',  model: 'IONIQ 5',         year: 2022, driver: 'Rafael Torres',   colour: 'White',   range: 303 },
  { id: 13, licensePlate: 'EV-013', make: 'Kia',      model: 'EV6',             year: 2023, driver: 'Nadia Kovač',     colour: 'Orange',  range: 310 },
  { id: 14, licensePlate: 'EV-014', make: 'Kia',      model: 'EV9',             year: 2024, driver: 'Owen Fitzgerald',  colour: 'Silver',  range: 304 },
  { id: 15, licensePlate: 'EV-015', make: 'BMW',      model: 'iX',              year: 2023, driver: 'Leila Ahmadi',    colour: 'Black',   range: 324 },
  { id: 16, licensePlate: 'EV-016', make: 'BMW',      model: 'i4',              year: 2022, driver: 'Tom Nguyen',      colour: 'Grey',    range: 301 },
  { id: 17, licensePlate: 'EV-017', make: 'Mercedes', model: 'EQS',             year: 2023, driver: 'Sara Ekström',    colour: 'White',   range: 350 },
  { id: 18, licensePlate: 'EV-018', make: 'Mercedes', model: 'EQB',             year: 2024, driver: 'Ali Hassan',      colour: 'Blue',    range: 243 },
  { id: 19, licensePlate: 'EV-019', make: 'Audi',     model: 'Q8 e-tron',       year: 2023, driver: 'Elena Popescu',   colour: 'Red',     range: 285 },
  { id: 20, licensePlate: 'EV-020', make: 'Audi',     model: 'A6 e-tron',       year: 2024, driver: 'Ben Cartwright',  colour: 'Silver',  range: 370 },
  { id: 21, licensePlate: 'EV-021', make: 'Volvo',    model: 'EX90',            year: 2024, driver: 'Chioma Obi',      colour: 'Black',   range: 300 },
  { id: 22, licensePlate: 'EV-022', make: 'Volvo',    model: 'C40 Recharge',    year: 2023, driver: 'David Müller',    colour: 'Green',   range: 226 },
  { id: 23, licensePlate: 'EV-023', make: 'Polestar', model: 'Polestar 2',      year: 2022, driver: 'Hannah Schmidt',  colour: 'White',   range: 270 },
  { id: 24, licensePlate: 'EV-024', make: 'Polestar', model: 'Polestar 3',      year: 2024, driver: 'Jorge Lima',      colour: 'Grey',    range: 315 },
  { id: 25, licensePlate: 'EV-025', make: 'Lucid',    model: 'Air Pure',        year: 2023, driver: 'Aisha Kamara',    colour: 'White',   range: 410 },
  { id: 26, licensePlate: 'EV-026', make: 'Lucid',    model: 'Air Grand Touring',year: 2024,driver: 'Nathan Brooks',   colour: 'Red',     range: 516 },
  { id: 27, licensePlate: 'EV-027', make: 'Nio',      model: 'ET5',             year: 2023, driver: 'Mei Lin',         colour: 'Blue',    range: 329 },
  { id: 28, licensePlate: 'EV-028', make: 'Nio',      model: 'ET7',             year: 2024, driver: 'Patrick Durand',  colour: 'Black',   range: 373 },
  { id: 29, licensePlate: 'EV-029', make: 'VW',       model: 'ID.4',            year: 2023, driver: 'Rosa Bianchi',    colour: 'White',   range: 275 },
  { id: 30, licensePlate: 'EV-030', make: 'VW',       model: 'ID.Buzz',         year: 2024, driver: 'Samuel Osei',     colour: 'Orange',  range: 230 },
  { id: 31, licensePlate: 'EV-031', make: 'Subaru',   model: 'Solterra',        year: 2023, driver: 'Yara El-Amin',    colour: 'Blue',    range: 222 },
  { id: 32, licensePlate: 'EV-032', make: 'Toyota',   model: 'bZ4X',            year: 2022, driver: 'Felix Wagner',    colour: 'Silver',  range: 252 },
  { id: 33, licensePlate: 'EV-033', make: 'Nissan',   model: 'Ariya',           year: 2023, driver: 'Grace Owusu',     colour: 'Grey',    range: 289 },
  { id: 34, licensePlate: 'EV-034', make: 'Nissan',   model: 'Leaf',            year: 2022, driver: 'Ivan Petrov',     colour: 'White',   range: 212 },
  { id: 35, licensePlate: 'EV-035', make: 'GMC',      model: 'Hummer EV',       year: 2023, driver: 'Jasmine Adeyemi', colour: 'Black',   range: 329 },
  { id: 36, licensePlate: 'EV-036', make: 'Cadillac', model: 'LYRIQ',           year: 2024, driver: 'Kevin O\'Brien',  colour: 'Red',     range: 314 },
  { id: 37, licensePlate: 'EV-037', make: 'Jeep',     model: 'Avenger EV',      year: 2023, driver: 'Laura Svensson',  colour: 'Green',   range: 248 },
  { id: 38, licensePlate: 'EV-038', make: 'Honda',    model: 'Prologue',        year: 2024, driver: 'Miguel Santos',   colour: 'Blue',    range: 296 },
  { id: 39, licensePlate: 'EV-039', make: 'Fisker',   model: 'Ocean',           year: 2023, driver: 'Nina Johansson',  colour: 'White',   range: 360 },
  { id: 40, licensePlate: 'EV-040', make: 'Canoo',    model: 'Lifestyle Vehicle',year: 2024, driver: 'Oscar Fleming',  colour: 'Yellow',  range: 250 },
]
